// export const host = process.env.REACT_APP_API_URL ?? 'https://afandi.mamatmusayev.uz'
export const host = process.env.REACT_APP_API_URL ?? 'http://172.15.228.58:8080'
export const about = "get/about/"
export const banner = "get/banner/"
export const team = "get/team/"
export const country = "get/country/"
export const postInfo = "postcomment/"
export const details = "orglistbycountry/"
export const getorg = "getorg/"
export const getreqs = "getreqs/"
export const sociallist = "sociallist/"